version: '3.8'
services:
  postgres:
    container_name: searxngDatabase
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: searxngDb
    ports:
      - "5434:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
